[linux]
192.168.211.189 ansible_user=usuario ansible_ssh_private_key_file=/var/www/html/proyecto/claveP ansible_python_interpreter=/usr/bin/python3

[windows]
192.168.1.20 ansible_user=Administrador ansible_password=TuPassword ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985
