---
- name: Actualizar m치quinas Windows remotamente usando SSH
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Instalar el m칩dulo PSWindowsUpdate (si no est치 instalado)
      win_powershell:
        script: |
          if (-not (Get-Command "Install-WindowsUpdate" -ErrorAction SilentlyContinue)) {
            Install-Module -Name PSWindowsUpdate -Force -Scope CurrentUser
          }
      register: pswindowsupdate_installed

    - name: Buscar actualizaciones de Windows
      win_powershell:
        script: |
          Install-WindowsUpdate -AcceptAll -AutoReboot
      register: update_result

    - name: Mostrar resultado de la actualizaci칩n
      debug:
        var: update_result.stdout_lines
